spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${SHOP_DB_URL}
    username: ${SHOP_DB_USERNAME}
    password: ${SHOP_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SHOP_JPA_DDL_AUTO:validate}
    show-sql: false
