server:
  port: ${STORE_SERVICE_PORT:8087}

spring:
  banner:
    location: classpath:banner.txt
    mode: console
  application:
    name: x-store-service
  profiles:
    default: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

x:
  http:
    logging:
      enabled: true
      server: x-store-service
      hop: "x-api-gateway → x-bff → x-store-service"
      hops:
        /api/v1/stores: "x-api-gateway → x-bff → x-store-service"
  redis:
    enabled: ${X_REDIS_ENABLED:true}
    key-prefix: x
    default-ttl: 10m
    caches:
      store-by-id: 15m
      stores-by-business: 5m
